title: Lerntagebuch
author: stemorit
description: > # this means to ignore newlines until "baseurl:"
  Dieses Lerntagebuch wird im Rahmen des Bachelorstudiengangs Information Science an der FH Graubünden geschrieben.


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
