title: Bibliotheks- und Archivinformatik
author: stemorit
description: > # this means to ignore newlines until "baseurl:"
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik


show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
