title: Lerntagebuch
author: stemorit
description: > # this means to ignore newlines until "baseurl:"
  Dieses Lerntagebuch wird im Rahmen eines Leistungsnachweises des Bachelorstudiengangs Information Science an der FH Graubünden geschrieben.

# social links
github_username:  stemorit # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
